# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShowAndHideVisibleLayerByType
                                 A QGIS plugin
 A simple plugin that allows you to turn visible vector and raster layers on and off.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-20
        copyright            : (C) 2023 by Tomasz Mazuga | MGGP S.A.
        email                : tmazuga@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShowAndHideVisibleLayerByType class from file ShowAndHideVisibleLayerByType.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .show_and_hide import ShowAndHideVisibleLayerByType
    return ShowAndHideVisibleLayerByType(iface)
